### ISSUE TITLE
 Неизвестная ошибка: 'token'

### ISSUE THREAD

**Issue by ananyevgv** [alryaz/hass-pik-comfort#1]
При попытке настроить интеграцию выдает ошибку "Неизвестная ошибка: 'token'"

**Comment by alryaz** [comment]
Пожалуйста, опишите, на каком конкретно этапе это происходит.

Вдобавок, только что запушил коммит, который добавляет более детальное описание причины возникновения "неизвестной ошибки" в лог (_home-assistant.log_). Если ошибка возникнет вновь, пожалуйста, пришлите описание ошибки из лога.

**Comment by ananyevgv** [comment]
После ввода смс 
Traceback (most recent call last):
  File "/config/custom_components/pik_comfort/config_flow.py", line 111, in async_step_otp_input
    user_input[CONF_TOKEN]
KeyError: 'token'

**Comment by alryaz** [comment]
Коммит, исправляющий данную мелочь, выпущен. Спасибо, что заметили!

**Comment by ananyevgv** [comment]
Смогу проверить только к концу недели, походу меня за частые запросы на смс забанили
Ошибка сервера (throttled): Запрос был проигнорирован. Expected available in 356891 seconds.

**Comment by ananyevgv** [comment]
Смогу проверить только к концу недели, походу меня за частые запросы на смс забанили
Ошибка сервера (throttled): Запрос был проигнорирован. Expected available in 356891 seconds.

**Comment by ananyevgv** [comment]
Все отлично
